Rocky/Controllers/ApplicationTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Rocky_DataAccess;
using Rocky_DataAccess.Repository.IRepository;
using Rocky_Models;
using Rocky_Utility;

namespace Rocky.Controllers
{
    [Authorize(Roles = WebConstants.AdminRole)]
    public class ApplicationTypeController : Controller
    {
        private readonly IApplicationTypeRepository _appTypeRepo;

        public ApplicationTypeController(IApplicationTypeRepository appTypeRepo)
        {
            _appTypeRepo = appTypeRepo;
        }

        public IActionResult Index()
        {
            IEnumerable<ApplicationType> applicationTypes = _appTypeRepo.GetAll();
            return View(applicationTypes);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApplicationType obj)
        {
            if (ModelState.IsValid)
            {
                _appTypeRepo.Add(obj);
                _appTypeRepo.Save();
                TempData[WebConstants.Success] = "Action Successfull!";
                return RedirectToAction("Index");
            }
            return View(obj);
            
        }

        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var obj = _appTypeRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationType obj)
        {
            if (ModelState.IsValid)
            {
                _appTypeRepo.Update(obj);
                _appTypeRepo.Save();
                return RedirectToAction("Index");
            }
            TempData[WebConstants.Success] = "Action Successfull!";
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var obj = _appTypeRepo.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var obj = _appTypeRepo.Find(id.GetValueOrDefault());
            _appTypeRepo.Remove(obj);
            _appTypeRepo.Save();
            TempData[WebConstants.Success] = "Action Successfull!";
            return RedirectToAction("Index");
        }
    }
}

Rocky/Views/ApplicationType/Create.cshtml
@model Rocky_Models.ApplicationType

@{
    ViewData["Title"] = "Create";
}


<form method="post" asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="border p-3 bg-white">
        <div class="form-group row">
            <h2 class="text-info pl-3">
                Add Application Type
            </h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">
                                <i class="fas fa-sign-out-alt"></i> &nbsp; Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>


</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky/Views/ApplicationType/Delete.cshtml
@model Rocky_Models.ApplicationType

@{
    ViewData["Title"] = "Edit";
}


<form method="post" asp-action="DeleteConfirmed" asp-route-Id="@Model.Id">
    <div class="border p-3">
        <div class="form-group row bg-white">
            <h2 class="text-info pl-3">
                Edit Application Type
            </h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" disabled/>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">
                                <i class="fas fa-sign-out-alt"></i> &nbsp;  Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>


</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky/Views/ApplicationType/Edit.cshtml
@model Rocky_Models.ApplicationType

@{
    ViewData["Title"] = "Edit";
}


<form method="post" asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="border p-3 bg-white">
        <div class="form-group row">
            <h2 class="text-info pl-3">
                Edit Application Type
            </h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100 text-white" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">
                                <i class="fas fa-sign-out-alt"></i> &nbsp; Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>


</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky/Views/ApplicationType/Index.cshtml
@model IEnumerable<ApplicationType>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3 bg-white">
    <div class="row pt-4">
        <div class="col-6">
            <h2>Application Types</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="ApplicationType" asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> &nbsp; Create New Application Type
            </a>
        </div>
    </div>
    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped">
            <thead>
                <tr class="text-center">
                    <th>
                        Id
                    </th>
                    <th>
                        Application Type Name
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @foreach (var row in Model)
                {
                    <tr>
                        <td width="20%" class="text-center">
                            @row.Id
                        </td>
                        <td width="50%">
                            @row.Name
                        </td>
                        <td>
                            <a asp-controller="ApplicationType" asp-route-Id="@row.Id" asp-action="Edit" class="btn btn-primary mx-2">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a asp-controller="ApplicationType" asp-route-Id="@row.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p class="text-info">No Application Types exist.</p>
    }
</div>